fix: apply no-pause rule recursively #147
cypress-io/eslint-plugin-cypress pull request #189
Opened 2024-04-24 14:07 UTC by tom9744

## Issue

The `cypress/no-pause` rule only applies to a parent node. 

## Changes

Convert the `isCypressCall` function into a recursive function to detect chained calls such as `cy.get("...").pause();`

2024-04-24 14:07 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cypress-io/eslint-plugin-cypress?pullRequest=189) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/cypress-io/eslint-plugin-cypress?pullRequest=189) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cypress-io/eslint-plugin-cypress?pullRequest=189) it.</sub>

2024-04-24 14:25 UTC, MikeMcC399 commented
@tom9744 

I would class your PR as a feature not a fix, since it extends the documented functionality, so the commit message would need to start with `feat:`,  for example: `feat: apply no-pause rule recursively`

You would also need to sign the SLA before the Cypress.io team could consider your PR.

2024-04-24 14:46 UTC, tom9744 commented
@MikeMcC399 Thank you for your guidance. I was on the fence about which prefix to choose.

2024-05-01 05:54 UTC, MikeMcC399 commented
@tom9744 

The documentation has been reworked since you submitted this PR. Could you rebase your PR? Sorry for the inconvenience!

2024-05-02 18:06 UTC, MikeMcC399 requested changes
Please resolve the conflicts due to changes that have been done since this PR was submitted.

2024-05-03 12:49 UTC, tom9744 commented
I rebased my PR and resolved all confilcts!

2024-05-03 14:03 UTC, MikeMcC399 commented
@tom9744 

Many thanks for your contribution! All looks good!

Tested against
https://github.com/cypress-io/cypress-example-kitchensink
using

```shell
npm install https://github.com/tom9744/eslint-plugin-cypress#user/tom9744/recursive-no-pause
```

and additional test-spec `cypress/e2e/pause.cy.js`

```js
/// <reference types="cypress" />

context('eslinting', () => {
  it('pausing', () => {
    cy.pause()
    cy.visit('https://example.cypress.io').pause()
  })
})
```

Add `"cypress/no-pause": "error"` to `.eslintrc` `rules`.
(The rule `no-pause` is not in the set of recommended rules.)

| eslint-plugin-cypress | result         | PR        |
| --------------------- | -------------- | --------- |
| `2.11.3`              | no failure (1) | -         |
| `2.12.1`              | (2)            | #85 + #86 |
| `3.0.3`               | (2)            | -         |
| PR #189               | (3)            | #189      |

(1) Note: rule `cypress/no-pause` not yet available in this version
(2) Only `cy.pause()` detected
(3) All uses of `.pause()` detected

2024-05-03 14:04 UTC, MikeMcC399 approved these changes
This is a good enhancement to the rule `cypress/no-pause` !

2024-05-03 14:18 UTC, jennifer-shehane approved these changes

2024-05-03 14:19 UTC, merged